version: "3.3"

networks:
  default:
    external:
      name: traefik-net

configs:
  telemetry_agent_config:
    file: ./agent-config.yml
  telemetry_collector_config:
    file: ./collector-config.yml

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
    restart: always

  # Collector
  telemetry_collector:
    image: omnition/opencensus-collector:latest
    command: ["--config=/etc/collector-config.yml", "--http-pprof-port=1777"]
    configs:
      - source: telemetry_collector_config
        target: /etc/collector-config.yml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    restart: always
    depends_on:
      - jaeger

  # Agent
  telemetry_agent:
    image: omnition/opencensus-agent:latest
    command: ["--config=/etc/agent-config.yml", "--http-pprof-port=1888"]
    configs:
      - source: telemetry_agent_config
        target: /etc/agent-config.yml
    ports:
      - "1888:1888"
      - "14268:14268"
      - "55678:55678"
      - "55679:55679"
    restart: always
    depends_on:
      - telemetry_collector
