version: "3"

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
    restart: always

  # Collector
  tracing_collector:
    image: omnition/opencensus-collector:latest
    command: ["--config=/etc/collector-config.yml", "--http-pprof-port=1777"]
    volumes:
      - ${PWD}/collector-config.yml:/etc/collector-config.yml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    restart: always
    depends_on:
      - jaeger

  # Agent
  tracing_agent:
    image: omnition/opencensus-agent:latest
    command: ["--config=/etc/agent-config.yml", "--http-pprof-port=1888"]
    volumes:
      - ${PWD}/agent-config.yml:/etc/agent-config.yml
    ports:
      - "1888:1888"
      - "14268:14268"
      - "55678:55678"
      - "55679:55679"
    restart: always
    depends_on:
      - tracing_collector

networks:
  default:
    external:
      name: traefik-net
