version: "3"

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
    restart: always

  # Collector
  oc-collector:
    image: omnition/opencensus-collector:latest
    command:
      ["--config=/etc/oc-collector-config.yaml", "--http-pprof-port=1777"]
    volumes:
      - ./oc-collector-config.yaml:/etc/oc-collector-config.yaml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    restart: always
    depends_on:
      - jaeger-all-in-one

  # Agent
  oc-agent:
    image: omnition/opencensus-agent:latest
    command: ["--config=/etc/oc-agent-config.yaml", "--http-pprof-port=1888"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    ports:
      - "1888:1888"
      - "14268"
      - "55678:55678"
      - "55679:55679"
    restart: always
    depends_on:
      - oc-collector
